name: conflibot
on: pull_request

jobs:
  conflibot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Warn potential conflicts
        uses: wktk/conflibot@v1.1.0
        with:
          github-token: ${{ secrets.CONFLICT_BOT_TOKEN }}
          exclude: |
            yarn.lock
            **/*.bin
