name: Crowdin Action

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */6 * * *'

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3.0.1

    - name: crowdin action
      uses: crowdin/github-action@1.4.7
      with:
        upload_translations: false
        download_translations: true
        upload_sources: true
        localization_branch_name: l10n_crowdin
        create_pull_request: true
        pull_request_title: 'New Crowdin translations'
        pull_request_body: 'New Crowdin pull request with translations'
        pull_request_labels: 'enhancement'
        config: 'crowdin.yml'
        crowdin_branch_name: master
        download_translations_args: '--all'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
